# Generated by Django 4.2.23 on 2025-11-13 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_auto_create_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
    ]
