# Generated by Django 4.2.23 on 2025-11-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[("New", "New"), ("Used", "Used")], default="New", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_zones",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="enable_digital_tryon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="enable_product_pricing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_from",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size_available",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
