# Generated by Django 4.2.23 on 2025-12-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_product_image_remove_product_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_locked",
            field=models.BooleanField(default=False),
        ),
    ]
