# Generated by Django 4.2.23 on 2025-12-12 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_price_locked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_locked",
        ),
    ]
