# Generated by Django 4.2.23 on 2026-04-05 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_product_price_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(
                upload_to="products/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm", "avi", "mkv", "3gp"]
                    )
                ],
            ),
        ),
    ]
