# Generated by Django 4.2.23 on 2026-04-05 21:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_productimage_image_alter_productvideo_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
