# Generated by Django 4.2.23 on 2026-06-21 01:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_productvideo_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
