# Generated by Django 4.2.23 on 2025-12-12 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0007_remove_product_price_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=255)),
                ("product_image", models.URLField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                (
                    "price_at_order",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "suggested_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "pickup_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transport_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("days_to_deliver", models.PositiveIntegerField(blank=True, null=True)),
                ("seller_notes", models.TextField(blank=True, null=True)),
                ("buyer_notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (seller review)"),
                            ("evaluating", "Evaluating (seller provided costs)"),
                            (
                                "completed_by_seller",
                                "Completed by seller (waiting buyer confirm)",
                            ),
                            (
                                "satisfactory",
                                "Satisfactory (buyer accepted, proceed to checkout)",
                            ),
                            (
                                "not_satisfactory",
                                "Not satisfactory (buyer asked for changes)",
                            ),
                            ("cancelled", "Cancelled"),
                            ("paid", "Paid"),
                            ("in_transit", "In transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="products.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
