# Generated by Django 4.2.23 on 2025-12-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pickup_location",
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_lga",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="collection_point",
            field=models.CharField(
                blank=True,
                help_text="Where buyer will collect the goods",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (seller review)"),
                    ("evaluating", "Evaluating (seller provided costs)"),
                    (
                        "completed_by_seller",
                        "Completed by seller (waiting buyer confirm)",
                    ),
                    (
                        "satisfactory",
                        "Satisfactory (buyer accepted, proceed to checkout)",
                    ),
                    ("not_satisfactory", "Not satisfactory"),
                    ("cancelled", "Cancelled"),
                    ("paid", "Paid"),
                    ("in_transit", "In transit"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
