# Generated by Django 4.2.23 on 2025-12-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_pickup_location_order_buyer_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_sent_to_seller",
            field=models.BooleanField(default=False),
        ),
    ]
