# Generated by Django 4.2.23 on 2025-12-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_is_sent_to_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
