# Generated by Django 4.2.23 on 2025-12-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_paystack_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paystack_reference",
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_verified",
            field=models.BooleanField(default=False),
        ),
    ]
