# Generated by Django 4.2.23 on 2025-12-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_order_paystack_reference_order_paid_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="extra_days_requested",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="payout_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="payout_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (seller review)"),
                    ("evaluating", "Evaluating (seller provided costs)"),
                    (
                        "completed_by_seller",
                        "Completed by seller (waiting buyer confirm)",
                    ),
                    (
                        "satisfactory",
                        "Satisfactory (buyer accepted, proceed to checkout)",
                    ),
                    ("not_satisfactory", "Not satisfactory"),
                    ("cancelled", "Cancelled"),
                    ("paid", "Paid"),
                    ("in_transit", "In transit"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
