# Generated by Django 4.2.23 on 2025-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_delivery_deadline_order_extra_days_requested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="agreed_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
