# Generated by Django 4.2.23 on 2025-12-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_agreed_days_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_att",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
