# Generated by Django 4.2.23 on 2025-12-28 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_paid_att"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid_att",
        ),
    ]
