# Generated by Django 4.2.23 on 2025-12-28 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_remove_order_paid_att"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="agreed_days",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivered_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_deadline",
        ),
    ]
