# Generated by Django 4.2.23 on 2025-12-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_remove_order_agreed_days_remove_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
