# Generated by Django 4.2.23 on 2025-12-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_order_delivery_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_verified_by_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_pdf",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_account_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
