# Generated by Django 4.2.23 on 2025-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_order_payment_verified_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="receipt_pdf",
            new_name="payout_receipt",
        ),
        migrations.AddField(
            model_name="order",
            name="seller_confirmed_payout",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_payout_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
