# Generated by Django 4.2.23 on 2025-12-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_rename_receipt_pdf_order_payout_receipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="extension_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="extension_requested_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="extension_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
