# Generated by Django 4.2.23 on 2025-09-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png", upload_to="avatars/"
            ),
        ),
    ]
