# Generated by Django 4.2.23 on 2026-01-02 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_profile_created_at_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook_link",
            field=models.URLField(
                blank=True, help_text="Facebook profile or page link", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_link",
            field=models.URLField(
                blank=True, help_text="Instagram profile link", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Current location (city / state)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tiktok_link",
            field=models.URLField(
                blank=True, help_text="TikTok profile link", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_link",
            field=models.URLField(
                blank=True, help_text="Twitter (X) profile link", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp contact number",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/default.png", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Primary phone number", max_length=20, null=True
            ),
        ),
    ]
