# Generated by Django 4.2.23 on 2026-01-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_profile_created_at_profile_facebook_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="facebook_link",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="instagram_link",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="tiktok_link",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="twitter_link",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="whatsapp_number",
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tiktok",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number e.g +2348012345678",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
