# Generated by Django 4.2.23 on 2026-06-21 01:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0006_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram",
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True, default=datetime.date(2026, 1, 1), max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tiktok",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number e.g +2348012345678",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
