# Generated by Django 4.2.23 on 2026-07-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_profile_bio_alter_profile_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Abia", "Abia"),
                    ("Adamawa", "Adamawa"),
                    ("Akwa Ibom", "Akwa Ibom"),
                    ("Anambra", "Anambra"),
                    ("Bauchi", "Bauchi"),
                    ("Bayelsa", "Bayelsa"),
                    ("Benue", "Benue"),
                    ("Borno", "Borno"),
                    ("Cross River", "Cross River"),
                    ("Delta", "Delta"),
                    ("Ebonyi", "Ebonyi"),
                    ("Edo", "Edo"),
                    ("Ekiti", "Ekiti"),
                    ("Enugu", "Enugu"),
                    ("Gombe", "Gombe"),
                    ("Imo", "Imo"),
                    ("Jigawa", "Jigawa"),
                    ("Kaduna", "Kaduna"),
                    ("Kano", "Kano"),
                    ("Katsina", "Katsina"),
                    ("Kebbi", "Kebbi"),
                    ("Kogi", "Kogi"),
                    ("Kwara", "Kwara"),
                    ("Lagos", "Lagos"),
                    ("Nasarawa", "Nasarawa"),
                    ("Niger", "Niger"),
                    ("Ogun", "Ogun"),
                    ("Ondo", "Ondo"),
                    ("Osun", "Osun"),
                    ("Oyo", "Oyo"),
                    ("Plateau", "Plateau"),
                    ("Rivers", "Rivers"),
                    ("Sokoto", "Sokoto"),
                    ("Taraba", "Taraba"),
                    ("Yobe", "Yobe"),
                    ("Zamfara", "Zamfara"),
                    ("FCT", "Federal Capital Territory (Abuja)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("tailor", "Tailor"),
                    ("fashion_designer", "Fashion Designer"),
                    ("fashion_brand", "Fashion Brand"),
                    ("fabric_vendor", "Fabric Vendor"),
                    ("others", "Others"),
                ],
                default="customer",
                max_length=30,
            ),
        ),
    ]
