# Generated by Django 4.2.23 on 2025-11-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_product_image_remove_product_video_and_more"),
        ("streaming", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamvideo",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stream_videos",
                to="products.product",
            ),
        ),
    ]
