# Generated by Django 4.2.23 on 2026-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("price_proposal", "Price Proposal"),
                    ("measurement_share", "Measurement Share"),
                    ("info", "Info"),
                ],
                default="info",
                max_length=32,
            ),
        ),
    ]
